# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  glad_config = debug
  photoengine_config = debug
  photoeditor_config = debug

else ifeq ($(config),release)
  glad_config = release
  photoengine_config = release
  photoeditor_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := glad photoengine photoeditor

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

glad:
ifneq (,$(glad_config))
	@echo "==== Building glad ($(glad_config)) ===="
	@${MAKE} --no-print-directory -C photoengine/deps/glad -f Makefile config=$(glad_config)
endif

photoengine:
ifneq (,$(photoengine_config))
	@echo "==== Building photoengine ($(photoengine_config)) ===="
	@${MAKE} --no-print-directory -C photoengine -f Makefile config=$(photoengine_config)
endif

photoeditor: photoengine glad
ifneq (,$(photoeditor_config))
	@echo "==== Building photoeditor ($(photoeditor_config)) ===="
	@${MAKE} --no-print-directory -C photoeditor -f Makefile config=$(photoeditor_config)
endif

clean:
	@${MAKE} --no-print-directory -C photoengine/deps/glad -f Makefile clean
	@${MAKE} --no-print-directory -C photoengine -f Makefile clean
	@${MAKE} --no-print-directory -C photoeditor -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   glad"
	@echo "   photoengine"
	@echo "   photoeditor"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"